From nvidia/cuda:10.1-devel-ubuntu18.04

RUN apt update -qq && apt install --yes -qq \
    cmake \
    git \
    openmpi-bin \
    libopenmpi-dev \
    jq \
    qpdf \
    xmlstarlet \
    xsltproc
CMD bin/bash
